[tool.poetry]
name = "binny"
version = "0.1.0"
description = "Bot for PursuedPyBear"
authors = ["Jamie Bliss <jamie@ivyleav.es>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
quart = "^0.11.3"
# Only to make sure we pull graphql-core from git
graphql-core = {git = "https://github.com/graphql-python/graphql-core.git"}
gqlmod = {git = "https://github.com/gqlmod/gqlmod.git"}
gqlmod-github = {git = "https://github.com/gqlmod/gqlmod-github.git", extras = ["app", "async"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
