#~github-async~

query get_check_suites($repo:ID!, $commit:GitObjectID!) {
    # Repo - > Commit -> CheckSuite
    node(id:$repo) {
        ... on Repository {
            object(
                oid: $commit
            ) {
                ... on Commit {
                    id
                    checkSuites(
                        first: 50
                    ) {
                        nodes {
                            # List
                            id
                            status
                            conclusion
                        }
                    }
                }
            }
        }
    }
}

query get_ref($repo:ID!, $name:String!) {
    node(id:$repo) {
        ... on Repository {
            ref(qualifiedName:$name) {
                id
                target {
                    id
                    oid
                }
            }
        }
    }
}

mutation trigger_deployment($repo:ID!, $ref:ID!) {
    createDeployment(input: {
        # CreateDeploymentInput
        repositoryId: $repo
        refId:$ref
    }) {
        # CreateDeploymentPayload
        deployment {
            id
        }
    }
}
