#~github~

mutation start_deploy($deployment:ID!) {
    createDeploymentStatus(input: {
        deploymentId: $deployment
        state: IN_PROGRESS
    }) {
        deploymentStatus {
            id
        }
    }
}

query get_deployment($deployment:ID!) {
    node(id:$deployment) {
        ... on Deployment {
            commit {
                id
                oid
            }
            ref {
                id
                name
                prefix
            }
        }
    }
}


mutation finish_deploy($deployment:ID!, $state:DeploymentStatusState!) {
    createDeploymentStatus(input: {
        deploymentId: $deployment
        state: $state
    }) {
        deploymentStatus {
            id
        }
    }
}
