name: gqlmod

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: gqlmod/check-action@trunk
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
